### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [Tox/toxic#248]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/Tox/toxic/blob/bd7b07315583a6c7af4b17fbc28823f7090ef1b3/build/Makefile#L1 "update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by stqism** [comment]
This isn't being changed, build systems are a fragile topic.
