### ISSUE TITLE
Toxic fails to display text in groupchat

### ISSUE THREAD

**Issue by zetok** [Tox/toxic#272]
How to reproduce (qTox needed):
1. Use Ratox to set null character at the end of nick.
2. Use qTox's tab autocompletion to "write" nick with appended '\0'
3. Toxic doesn't display anything after '\0'
![pls fix](https://cloud.githubusercontent.com/assets/3148759/4705614/7b73cd50-587d-11e4-9079-c980d59164dd.png)

Please fix.

**Comment by louipc** [comment]
I've experienced this bug as well. I had a null in the nick after using ntox.

**Comment by ProMcTagonist** [comment]
>Also I don't see anything wrong with those screenshots.

The part where no more text gets displayed, I think.

**Comment by optimumtact** [comment]
Why won't you fix this Freeg?

**Comment by JFreegman** [comment]
@optimumtact Because as far as I can tell this bug is a result of ancient toxcore behaviour and is no longer possible to reproduce without modifying the source. If someone can prove me wrong I'll look into it.
