### ISSUE TITLE
openalut

### ISSUE THREAD

**Issue by mooin** [Tox/toxic#287]
Hi,
i use Fedora and yum doesn't has openalut (or libalut-dev). 
u used it in:
 
Sound notifications
openalut (for Debian based systems, 'libalut-dev')

in the Document:
https://github.com/Tox/toxic/blob/master/README.md

i couldn't complie without this lib so i used instead freealut and it worked.
I don't know if this is really an issue for u guys, i just wanted to let u know.
Good luck and keep rocking!

**Comment by Ansa89** [comment]
That's only a naming matter: Fedora package is called "freealut", while Debian calls it "libalut".
Same software, different package name.
