### ISSUE TITLE
Import tox id

### ISSUE THREAD

**Issue by idmacdonald** [Tox/toxic#295]
Is it possible to set Toxic to use a pre-exisiting tox id on startup? Or import a tox id generated in another program?

I have a tox id generated in qTox, which I have been able to export/import to qTox installations on a number of different devices. It would be great to be able to import a tox id into toxic.

I can see that both qtox and toxic edit my ~/.config/tox/data file when they run, but I don't seem to be able to use the same tox id in toxic and qTox or be able to import a pre-existing tox id into toxic. I am not sure if this is a support or feature request, but any help would be appreciated.

Cheers,
-Ian

**Comment by dubslow** [comment]
qTox reads, but does not write, the `data` file. That's deprecated, and in the future will not even read `data`. The standard is to use the .tox file extension for your profiles. I don't know how Toxic works in this regard.

**Comment by idmacdonald** [comment]
I have found that I can take a qTox profile export .tox file and rename it to .ratox.tox and ratox will load the profile file. However, I've not been able to get toxic to do the same thing.

**Comment by JFreegman** [comment]
The -f flag will either use an existing data file, or create one if it doesn't exist. for example, `toxic -f ~/.config/tox/qtox_profile.tox`

**Comment by dubslow** [comment]
@JFreegman Consider changing the default to toxic.tox :) That way other clients will see it no problem, and Toxic will also see other clients' profiles no problem.

**Comment by JFreegman** [comment]
I'll consider it

**Comment by idmacdonald** [comment]
I see now that I can export a tox profile from qTox and then use toxic -f SOMEID.tox to load that profile into toxic. I thought I had tried that before, but I guess I made some sort of error. Thanks for your help!

**Comment by JFreegman** [comment]
no problem
