### ISSUE TITLE
Avoid non-posix option in sed.

### ISSUE THREAD

**Issue by henriqueleng** [Tox/toxic#307]
I'm trying to install toxic on a non-Linux system, that don't use the gnu sed.
But the install.mk file makes use of -i sed option, which is not posix, and isn't supported 
by other systems. (http://pubs.opengroup.org/onlinepubs/009604599/utilities/sed.html)
Can you please change this behavior to improve portability?

**Comment by JFreegman** [comment]
@Ansa89 is this possible to fix?
