### ISSUE TITLE
Tox fails when run through torsocks

### ISSUE THREAD

**Issue by yurivict** [Tox/toxic#320]
When UDP option is checked in client, tox crashes (tox==null). It starts when UDP traffic is sent and lost, but when torsocks explicitly fails socket(2) calls it crashes silently. It should say "Unable to create UDP socket", and exit gracefully.

**Comment by JFreegman** [comment]
Can you give me the exact steps to reproduce this please?

**Comment by yurivict** [comment]
Steps:
* Install torsocks from here https://github.com/dgoulet/torsocks/
* Have tor running
* Choose option 'Enable UDP' in client (I use qTox)
* Run 'torsocks qTox'
* Observe it crash

**Comment by JFreegman** [comment]
@yurivict This is the toxic repo. You want to head over to the qTox repo and make an issue there. https://github.com/tux3/qTox/issues/

Or if you think it's a toxcore problem that's unrelated to qTox, try the toxcore repo: https://github.com/irungentoo/toxcore/issues

**Comment by yurivict** [comment]
Sorry, I confused repos. This is for toxcore.
