### ISSUE TITLE
Toxic incompatible with qtox

### ISSUE THREAD

**Issue by jimrustle** [Tox/toxic#324]
The toxic client works fine when the other user is using toxic, but if they are using qtox, then:

A) the qtox user immediately sees a 4GiB file transfer (accepting it from qtox does nothing)
B) the first four characters of any message sent by the toxic client user is cut off, and the remaining characters are sent to the qtox user
C) any message received from the qtox user to the toxic client is blank/appears as an empty line

**Comment by jimrustle** [comment]
qTox version:  17:27:01 Mar 22 2015 ( 1427059505 ), from the Ubuntu repository
Toxic version:  TOXIC 0.6.0_r1516, also tested with TOXIC 0.6.0 from the Ubuntu repository -- same bugs

**Comment by JFreegman** [comment]
This is due to the fact that Toxic has been upgraded to use the new API while qTox hasn't yet. There were some protocol changes which break compatibility between the old and new API. This should be resolved as soon as qTox is ported to the new API.

**Comment by jimrustle** [comment]
Alrighty, then. I guess the solution is to just wait. Thanks!

**Comment by v6** [comment]
// , Is it compatible with μTox, at least?

**Comment by JFreegman** [comment]
Toxic is compatible with all active clients as of right now
