### ISSUE TITLE
tox_self_get_* functions do not terminate strings

### ISSUE THREAD

**Issue by mustrumr** [Tox/toxic#327]
$ toxic
     [Offline] <name> :  ~?~?~?
    /status online " "
     [Offline] <name> :  
    /quit
    $ toxic
     [Offline] <name> :  ~?~?~?

Gets annoying pretty quickly. Affected files:
- src/term_mplex.c in mplex_timer_handler
- src/prompt.c in prompt_onDraw

**Comment by JFreegman** [comment]
should be resolved https://github.com/Tox/toxic/commit/0bc610e18dc22112d57c744db13c66e385cccf15
