### ISSUE TITLE
Toxic session aborted with error code 2 (tox_new() failed)

### ISSUE THREAD

**Issue by emanueLczirai** [Tox/toxic#328]
$ toxic
Creating new data file. Would you like to encrypt it? Y/n (q to quit) 
n
...
Toxic session aborted with error code 2 (tox_new() failed)

Even if I choose Y (and enter a pass twice) it will still fail with the same error.

$ echo $TERM
rxvt-unicode-256color

$ uname -a
Linux manji 4.0.0-rc6-g6c310bc #58 SMP Wed Apr 1 06:56:03 CEST 2015 x86_64 GNU/Linux

What other info should I give?

Actually if I do:
$ toxic -4
it works

I should mention I don't have ipv6 in kernel...
$ zcat /proc/config.gz |grep -i ipv6
# CONFIG_IPV6 is not set

**Comment by stal888** [comment]
Well, yes. `-4` puts toxic into IPv4 only mode, which should work better on systems that don't have IPv6 in the kernel...

**Comment by JFreegman** [comment]
It should try to fall back to ipv4 without you specifying the option now. https://github.com/Tox/toxic/commit/82e76a3b5b92a401547e40a1c5ac1ed520e953ea

Let me know if it works

**Comment by emanueLczirai** [comment]
Tested. Works as specified! Thank you!

$ toxic -b
```
stderr enabled
Falling back to ipv4
Avatar is not set.
```
