### ISSUE TITLE
tox_new TOX_ERR_NEW_LOAD_BAD_FORMAT error is non fatal.

### ISSUE THREAD

**Issue by irungentoo** [Tox/toxic#333]
https://github.com/Tox/toxic/blob/4d73f8b24164a452b8dd3dbf42ccca318f123ba0/src/toxic.c#L643-L646

Check if tox_new returned null to see if the error was fatal or not.

This is documented here: https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.h#L510-L511

**Comment by JFreegman** [comment]
fixed https://github.com/Tox/toxic/commit/414f58d89686a8d19299c5ae1e7f5daab1682699
