### ISSUE TITLE
Toxic crashes on startup

### ISSUE THREAD

**Issue by nikwen** [Tox/toxic#335]
I installed the lasted version from the Linux repo on my Ubuntu 15.04 machine.
Since a few days (less than a week) Toxic crashes with the following error message on startup:

```
nikwen@nikwen:~$ toxic
Toxic session aborted with error code 3 (tox_new returned fatal error %d)
```

**Comment by JFreegman** [comment]
Could you try running it as super user?

**Comment by nikwen** [comment]
Then it says:

```
Creating new data file. Would you like to encrypt it? Y/n (q to quit)
```

**Comment by JFreegman** [comment]
So it works now? I'm not sure what would cause that but obviously you don't have the proper permissions to run it as a normal user.

**Comment by nikwen** [comment]
No, it doesn't. After typing "n" and pressing enter, I get the same error as before:

```
Toxic session aborted with error code 3 (tox_new returned fatal error %d)
```

**Comment by JFreegman** [comment]
hmm, well here's the description of that error from the toxcore API:
`
    /**
     * The function was unable to bind to a port. This may mean that all ports
     * have already been bound, e.g. by other Tox instances, or it may mean
     * a permission error. You may be able to gather more information from errno.
     */
`

Any clues?

**Comment by ZoeDev** [comment]
I have the same problem (Ubuntu 15.04 as well).

**Comment by nikwen** [comment]
No, I don't have any idea here. It used to work until a few days ago when Toxic suddenly stopped working. It was about the same day when uTox and qTox migrated to the new API (can't say whether it was *exactly* that day though). Maybe it's related to the Jenkins build mechanism?!

tox_new() seems to work fine in uTox and qTox as well as in the Tox client I'm writing myself.
(Toxic is awesome for testing it! Thanks. :smile:)

**Comment by nikwen** [comment]
```
nikwen@nikwen:~$ toxic -4
Toxic session aborted with error code 3 (tox_new returned fatal error %d)
```

**Comment by JFreegman** [comment]
if you could find an older version of toxic that works that would be helpful

**Comment by nikwen** [comment]
Ok, I went back to version 0.6.0-416 and it still doesn't work. However, it worked until recently.
May be an issue in Ubuntu 15.04...

**Comment by nikwen** [comment]
What stopped me from compiling from source were the dependencies...
I could install them though. Meanwhile, I found the reason for the `%d` in the output. You'll have a PR for that in a minute.

**Comment by nikwen** [comment]
Sorry, forget about that. I didn't look at your source code properly. :blush:

**Comment by nikwen** [comment]
Built from source and everything is working fine. Seems to be an issue with the Jenkins builds...

**Comment by JFreegman** [comment]
strange. @stqism any ideas?

**Comment by nikwen** [comment]
Well, it could actually be that the debs are compiled for a specific Debian or Ubuntu version and that these are somehow incompatible with the latest Ubuntu release. That's what I would guess at least.

**Comment by urras** [comment]
I'll take a look at the Jenkins builds, but I since I wasn't the one who configured them, @stqism might have to help out a bit. 

@nikwen, if you don't mind me asking, what architecture are you on?

**Comment by nikwen** [comment]
@urras Thanks. I'm on x86_64.

**Comment by nikwen** [comment]
Version 0.6.0-484 seems to work now. :)

**Comment by ivasim** [comment]
Hi, I had the same problem recently and I discovered that the cause was in incompatible toxic.conf file in .config/tox/ directory so I deleted it and copied an example one from /usr/share/toxic. Older versions had some differences in paths for sound files, maybe changes from absolute to relative paths, can't remember now, because I have deleted the older one unfortunately.

**Comment by nikwen** [comment]
I don't think this was related to the toxic.conf file as it suddenly started working again.
Meanwhile, I've now got confirmation from @ZoeDev that it's working fine on Linux Mint as well so I'll close this.

Thank you very much for fixing the Linux builds. :)
