### ISSUE TITLE
Blocking a contact doesn't seem to work

### ISSUE THREAD

**Issue by ivasim** [Tox/toxic#341]
Nothing happens when I press B key, blocklist is not being populated.
Toxic v0.6.0-608 on Debian Jessie 64bit.
Also it would be nice to implement some indicator on contact list to easily recognize blocked contacts?

**Comment by JFreegman** [comment]
you can use the left and right arrow keys to navigate between the contact list and block list. can you give me a better idea of exactly what you're doing?

**Comment by ivasim** [comment]
Sorry, now it works as it should, I did and upgrade to v0.6.0-610, maybe something was wrong with previous release. I'm sure that pressing "B" on keyboard didn't work and I could not block a contact.
