### ISSUE TITLE
[Invalid UTF-8]

### ISSUE THREAD

**Issue by alexkaskasoli** [Tox/toxic#344]
I've just installed toxic. I'm chatting with a friend who can see the messages I send him but I get "empty" messages from him. Example chat:

    me: hello
    him:
    me: can you read me?
    him:
    ...

When I receive his messages I get a notification in the top right of my screen `[Invalid UTF-8]`.

Any suggestions?

**Comment by JFreegman** [comment]
I'd need to know what he's actually sending you. There are a few newer UTF8 char sets that ncurses doesn't support, but that shouldn't happen with any normal text.

**Comment by alexkaskasoli** [comment]
Hi @JFreegman 
He's sending me normal stuff, I asked him to type letter-for-letter "hello".
He's under Windows 7 and I'm under Fedora, he's using uTox, I've talked to him before on a Linux uTox client.

**Comment by JFreegman** [comment]
@alexkaskasoli Is it possible that one of you is using a very old version of your respective client?
