### ISSUE TITLE
Remove/Replace links to libtoxcore.so

### ISSUE THREAD

**Issue by blobgo** [Tox/toxic#349]
You have already replaced links to tox.im, but all links to libtoxcore.so should be replaced or at least marked with a biog warning sign too.

[Because they should (also) be considered compromised] (https://blog.tox.chat/2015/07/current-situation-3).

**Comment by Don42** [comment]
@blobgo I can't find any links to libtoxcore.so. Where did you see them. The only hit for "libtoxcore.so" I get is for the name of the library, which as far as I know has not changed.

**Comment by JFreegman** [comment]
I removed them a few weeks ago
