### ISSUE TITLE
Add a configure option or something to change the location of the config directory

### ISSUE THREAD

**Issue by BlacklightShining** [Tox/toxic#352]
Some of us would rather just use `~/.toxic` than `~/Library/Application Support/tox`. (Related to #237.)

**Comment by louipc** [comment]
On Mon 14 Sep 2015 19:43 -0700, Blacklight Shining wrote:
> Some of us would rather just use `~/.toxic` than `~/Library/Application
> Support/tox`. (Related to #237.)

Well it would have to be a command line switch.
Otherwise how would toxic know where the config to set a different config
location is?

**Comment by JFreegman** [comment]
There is a commandline option for that. `toxic --help`.
