### ISSUE TITLE
Does Toxic support proxy?

### ISSUE THREAD

**Issue by hackerkid** [Tox/toxic#355]
I am on a proxy network and is having a hard time getting my client send a friend request. Does toxic support proxy?

**Comment by JFreegman** [comment]
Yes, toxic supports proxies. Use the --help option or read the manual for usage instructions.

**Comment by hackerkid** [comment]
Thanks :+1:

**Comment by linux0ne** [comment]
@JFreegman 
I didn't find the proxy Settings option, with a detailed description of how to set up, for example.

**Comment by JFreegman** [comment]
@linux0ne You run toxic with the proxy option and the IP and port that you want to use as arguments. See: `toxic --help`
